### ISSUE TITLE
Fix Find Garages by IP address

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/parkify#2]
**Describe the bug**
Find Garages using IP Adress doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://parkify-web.herokuapp.com/garage/find/
2. Click on 'Find by IP'
3. 'Internal Server Error' Appears.

**Expected behaviour**
Find the nearest garage and show the location on the map.

**Comment by Villain45** [comment]
**Would like to work on this......**
